### ISSUE TITLE
인벤토리, 오브젝트 아이템 드랍 이벤트 구현

### ISSUE THREAD

**Issue by SHIN-MINGYU** [hutari-org/pixel-resistance#11]
## Todo

- [ ] 인벤토리 UI구현 (틀만)
- [ ] 인벤토리 로직 구현
- [ ] 아이템 드랍 로직 구현
