### ISSUE TITLE
오브젝트 생성,, 상호작용 추가

### ISSUE THREAD

**Issue by SHIN-MINGYU** [hutari-org/pixel-resistance#4]
## Todo 
- [x]  맵 생성

- [x]  오브젝트(일단 나무) 생성 및 물리(부딪힘, HP제거 로직 추가)

- [x] 유저가 클릭이벤트를 발생시켰을때 해당 부분의 특정 각도 만큼 상호작용(공격이벤트) 가 발생시키게 할것

- [x] 이벤트 범위 안에 오브젝트가 위치해 있을때, 오브젝트의 hp제거 로직 발생
